FROM wordpress:latest

EXPOSE 80

# Set workdir
WORKDIR /var/www/html

# Copy php uploads config file
COPY ./wordpress/uploads.ini /usr/local/etc/php/conf.d/uploads.ini

# Copy wordpress content
COPY ./wordpress/content_for_setup/* /usr/src/wordpress/wp-content/
